services:
  web-portfolio:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: web-portfolio
    restart: on-failure
    networks:
      - portfolio

  web-caddy:
    image: caddy:latest
    container_name: web-caddy
    restart: on-failure
    volumes:
      - ./Caddyfile:/etc/caddy/portfolio/Caddyfile
      - pf_caddy_data:/data
      - pf_caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - portfolio

networks:
  portfolio:
    name: portfolio-network
    driver: bridge
volumes:
  pf_caddy_data:
  pf_caddy_config: